import { useRouter } from 'next/dist/client/router';
import Head from 'next/head';
import Image from 'next/image';
import { Card } from '../components/Card';
import styles from '../styles/Home.module.css';
import { deleteListing, getListingImages, getListings } from './api/listings';

export default function Home({ listings }: { listings: any }) {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="">
          {listings
            // .filter((listing) => listing.created_by === user.email)
            .map((listing: any) => (
              <Card
                // onDelete={() => onDelete(listing.id)}
                listing={listing}
                key={listing.id}
              />
            ))}
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps(_context: any) {
  const { listings, error } = await getListings();
  if (error) {
    console.log('error while fetching listing: ', error);
  }

  for await (let listing of listings) {
    const images = await getListingImages(listing);
    listing.images = images;
  }
  return {
    props: {
      listings,
    },
  };
}
